$schema: 'mcp-agent.config.schema.json'
execution_engine: asyncio

mcp:
  servers:
    fetch:
      command: 'uvx'
      args: ['mcp-server-fetch']
    filesystem:
      command: 'npx'
      args:
        [
          '-y',
          '@modelcontextprotocol/server-filesystem',
          'F:/yexin/redgenius/black',
        ]

openai:
  base_url: https://api.deepseek.com/v1
  default_model: deepseek-chat
